### ISSUE TITLE
How to determine the difficulty level

### ISSUE THREAD

**Issue by zswuser** [devichand579/HPT#3]
Hello, thank you for your open-source work. I would like to inquire about the process when using the HPF framework for inference. The strategy is determined based on the difficulty level of the question, and this difficulty level is determined by the prompt-selector (llama-3 8B), correct? Please forgive me for not understanding the specific process of the framework during inference.

**Comment by devichand579** [comment]
@zswuser The level is determined by human assessment based on their cognitive experiences with the prompting strategies, but in Adaaptive-HPF we use the prompt-selector to select the level

**Comment by zswuser** [comment]
thank you for your patient response!
